---
# handlers file for ansible-role-mariadb

- name: "service mariadb restart"
  service:
    name: mysql
    state: restarted

- name: "service mariadb start"
  service:
    name: mysql
    state: started

- name: "service mariadb stop"
  service:
    name: mysql
    state: stopped
